#!/usr/bin/env python

import os
import sys
from transformers import AutoTokenizer

sys.path.append(".")

from predict import MODEL_NAME, MODEL_CACHE

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    use_fast=True,
    cache_dir=MODEL_CACHE,
)
